# site settings
title: Kashish Srivastava
subtitle: portfolio
email: kashish.srivastava014@gmail.com
description: A portfolio/blog site
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 
city: Shimla
state: HP
zip_code: 
country: India
phone: +91 7018242486

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/cannibalcheeseburger
gitlab_url: https://gitlab.com/cannibalcheeseburger
googleplus_url: 
instagram_url: https://instagram.com/cannibalcheeseburger
linkedin_url: https://www.linkedin.com/in/kashish-srivastava-473b4b10a/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/cannibalcheese

# build settings
markdown: kramdown

sass:
  style: compressed
