menu:
- {name: 'people', url: '/people'}
- {name: 'publications', url: '/publications'}
- {name: 'courses', url: '/courses'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

people:
- {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
- {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
- {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

courses:
- {name: 'AIL701 MATHEMATICAL FOUNDATIONS OF MINDS', url: 'https://web.iitd.ac.in/~sahasudipan/courses/AIL701_2401.html'}
- {name: 'ELL784 INTRODUCTION TO MACHINE LEARNING', url: 'https://www.cse.iitd.ac.in/~sumantra/courses/ml/ml_pg.html'}
- {name: 'COL764 INFORMATION RETRIEVAL AND WEB SEARCH ', url: 'https://www.cse.iitd.ac.in/~srikanta/course/col764-2024/'}
- {name: 'COL671 ARTIFICIAL INTELLIGENCE', url: 'https://lily-molybdenum-65d.notion.site/COL333-COL671-Introduction-to-Artificial-Intelligence-1191ade548d442f2b4da46a6cbe32c4d'}
- {name: 'AIL862 SPECIAL TOPICS IN COMPUTER VISION', url: 'https://web.iitd.ac.in/~sahasudipan/courses/AIL862_2402.html'}
- {name: 'AIL721 Deep Learning ', url: 'https://jamesarambam.me/dl'}
- {name: 'COL761 DATA MINING', url: 'https://homecse.iitd.ac.in/col761-data-mining/'}


social:
- {icon: 'github', link: 'https://github.com/cannibalcheeseburger'}
- {icon: 'twitter', link: 'https://x.com/cannibalcheese'}
- {icon: 'instagram', link: 'https://www.instagram.com/cannibalcheeseburger/'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/kashish-srivastava-473b4b10a/'}

contacts:
- {name: 'Kashish Srivastava', title: 'MTech AI (MINDS)', department: 'School of AI', institution: 'IIT Delhi', institution_address: 'Hauz Khas, New Delhi, Delhi 110016', entry number: '2024AIB2289', email: 'kashish.srivastava014@gmail.com', lab: 'ScAI Lab, 5th floor,99C', image: 'assets/img/contact.jpg'}
